blank_issues_enabled: false
contact_links:
  - name: Questions / Support
    url: https://github.com/xuevertalex-web/RFMapToolMain/discussions
    about: Please use Discussions for questions and help.
